kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: echo-http2
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress=true"
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8080
    listenAddress: 127.0.0.1
    protocol: TCP
  - containerPort: 8443
    hostPort: 8443
    listenAddress: 127.0.0.1
    protocol: TCP
  - containerPort: 8444
    hostPort: 8444
    listenAddress: 127.0.0.1
    protocol: TCP
  - containerPort: 50051
    hostPort: 50051
    listenAddress: 127.0.0.1
    protocol: TCP
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
